---
title: "Hmwk2"
author: "Alicia Yang"
date: "10/4/2019"
output: github_document
---

```{r problem 1.1}
library(tidyverse)
library(readxl)

Trash_Wheel_data = 
  read_excel("./Hmwk2data/Trash_Wheel.xlsx", sheet = "Mr. Trash Wheel") %>%
  janitor::clean_names() %>%
  select(-x15, -x16, -x17) %>%
  drop_na(dumpster, year, date) %>%
  mutate(
  sports_balls = round(sports_balls, digits = 0))

as.integer(pull(Trash_Wheel_data, sports_balls))
```

```{r problem 1.2}
Precipitation2018_data =
  read_excel("./Hmwk2data/Trash_Wheel.xlsx", sheet = "2018 Precipitation") %>%
  janitor::clean_names() %>%
  drop_na() %>%
  rename(month = precipitation_in) %>%
  rename(in_precipitation = x2) %>%
  mutate(
    year = 2018)

Precipitation2017_data =
  read_excel("./Hmwk2data/Trash_Wheel.xlsx", sheet = "2017 Precipitation") %>%
  janitor::clean_names() %>%
  drop_na() %>%
  rename(month = precipitation_in) %>%
  rename(in_precipitation = x2) %>%
  mutate(
    year = 2017)

precipitation_data = 
  left_join(Precipitation2017_data, Precipitation2018_data, by = "month")

month.name = (pull(precipitation_data, month))
```

```{r problem 2.1}
polls_data = 
  read_csv("./fivethirtyeight_datasets/pols-month.csv") %>%
  janitor::clean_names() %>%
  separate(col = mon, into = c("yr", "month", "day")) %>%
  rename(month = month.name(mon)) %>%
  mutate(
    president = gop, dem) %>%
  select(-prez_dem, -prez_gop, -day)
```

```{r problem 2.2}
snp_data = 
  read_csv("./fivethirtyeight_datasets/snp.csv") %>%
  janitor::clean_names() %>%
  separate(col = date, into = c("yr", "month", "day")) %>%
  rename(month = month.name(mon)) %>%
  select(-day) %>%
  select(year, month, close)
```

```{r problem 2.3}
unemployment_data = 
  read_csv("./fivethirtyeight_datasets/unemployment.csv") %>%
  janitor::clean_names() %>%
  pivot_longer(
    Jan:Dec, 
    names_to = "month", 
    values_to = "unemploy_rate"
  )
```

```{r problem 2.4}
thirtyfiveeight_data = 
  left_join(polls_data, snp_data)
  inner_join(polls_data, snp_data )
  anti_join(snp_data, polls_data)
  anti_join(polls_data, snp_data)

thirtyfiveeight_final_data = 
  left_join(thirtyfiveeight_data, unemployment_data)
  inner_join(thirtyfiveeight_data, unemployment_data)
  anti_join(unemployment_data, thirtyfiveeight_data)
  anti_join(thirtyfiveeight_data, unemployment_data)
```

```{r problem 3.1}
baby_names_data =
  read_csv("./Hmwk2data/Popular_Baby_Names.csv") %>%
  janitor::clean_names() %>%
  distinct() %>%
  mutate(
    ethnicity = 
      factor(levels = 1:4, labels = c("Asian and Pacific Islander", "Black Non Hispanic", "White Non Hispanic", "Hispanic"))
  )
```

```{r problem 3.2}
Olivia_data = 
  filter(baby_names_data, childs_first_name == "Olivia")
```
